### ISSUE TITLE
Find source of Travis failing but test locally passing for marketgui-new branch's MarketActivityTest

### ISSUE THREAD

**Issue by AmroAbdrabo** [Zeavee/Run0rD1e#234] opened 2020-05-09 07:10 UTC

**Comment by zyuiop** [comment] 2020-05-09 19:00
Hi,
Travis, as any CI, executes an environment which is different than the one you run on your machine. First, the VMs used by Travis don't have hardware acceleration for graphics, therefore the emulator has a small window size (< 480p). Then, the emulator in the VM uses an emulated arm CPU instead of a x86 image as you do on your computer. Other differences may be found in the documentation.

Sometimes, your tests will pass locally, and fail on travis. It can often be explained by the differences between your environment and travis, and it therefore indicates that your app would not run correctly in all situations. Diagnosing these problems will be part of your job as a software engineer and is part of your job today as a student in SDP.

We can help you to figure this out if, after multiple attempts, you cannot find the cause of the problem. For this, we do however need to have as much information as you can provide: what did you try, what seemed to work, which builds seem to fail and with what error... We are not going to do all the trial and error for you, as it is supposed to be your task as a student.

Cheers,
Louis

**Comment by AmroAbdrabo** [comment] 2020-05-09 23:53
Ok so I'm working on marketgui-new branch and I literally tried everything (like _literally_ all the things I can) but I can't seem to fix "error performing single click" on shieldImg (shieldImg is an imageButton) and I know for fact that MarketActivity is loaded onto the screen since it sees the "Market" label at the top.

**Comment by AmroAbdrabo** [comment] 2020-05-10 02:05
@zyuiop @dialexo 
Update: Sacha removed cards and the button was clicked on Travis, but it's beyond me and Sacha's comprehension why it can't click on a button inside a card. Also, removing the cards is too big of a compromise on the look-and-feel of the MarketActivity. I'm not trying to make an award-winning user interface but I'm also not going to make a user interface that looks like the Nokia 3310

**Comment by zyuiop** [comment] 2020-05-10 12:03
Did you try running locally with a small screen size for the emulator, to check that all the elements render properly on such a small screen? And did you try using the same emulator version as in Travis (still using the smaller screen size)? You can also do that + use an arm emulator. The idea is to try to reproduce locally the Travis environment to see the bug from your own eyes - if possible.

**Comment by AmroAbdrabo** [comment] 2020-05-10 18:59
OK so I tested on two phone emulators: the 3.4'' Nexus One (onClick failed initially locally then it passed after I fixed it) and the 3.3'' WQVGA which also passed locally. (Obviously all using API 28). Basically, the 3.4'' Nexus One build that passed locally failed the onClick test on Travis and the WQVGA failed **_every_** espresso test on Travis. I have literally already passed 30 hours on this because of a ridiculous CI platform

**Comment by zyuiop** [comment] 2020-05-10 22:13
Hi,
As I mentioned, you can also try to use the x86 emulator on travis.
Use `sys-img-x86-android-26` in the `components` section (replacing your current sys-img) of the `.travis.yml` file.
You'll find more help on the documentation: https://docs.travis-ci.com/user/languages/android/#ci-environment-for-android-projects

**Comment by Zeavee** [comment] 2020-05-11 22:54
Hello, it now works after we followed a post on the forum.
Thank you for your answers

**Closed by Zeavee** 2020-05-11 22:54 UTC
